### ISSUE TITLE
DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead

### ISSUE THREAD

**Issue by braco** [nickjj/manifest-revision-webpack-plugin#52]
```
(node:58259) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at Walker.file (manifest-revision-webpack-plugin/index.js:149:30)

node:58259) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at ManifestRevisionPlugin.apply (manifest-revision-webpack-plugin/index.js:178:14)
```

**Comment by braco** [comment]
Looks like there's a PR

https://github.com/nickjj/manifest-revision-webpack-plugin/pull/48

**Comment by braco** [comment]
Your plugin is broken on Webpack 5 because of this warning @nickjj

**Comment by nickjj** [comment]
@braco does #48 fix this?

**Comment by braco** [comment]
Believe so, but I switched to @5kyc0d3r's fork:
https://github.com/5kyc0d3r/flask-webpack-fork
that uses
https://github.com/danethurber/webpack-manifest-plugin
Might be a good migration recommendation if you want to let these projects go?

PS, _thank you_ for the work on these

**Comment by nickjj** [comment]
Yeah I would switch to a different library. I really should archive this project as I haven't used it in a very long time and I don't like seeing so many people try to use it and then it blows up since it's not compatible with newer versions of Webpack.

My personal opinion is that the md5 hashing of files should really be controlled by whatever web framework you use since your web framework's template system needs a manifest file in the end to do the look up.

You need both halves (the manifest file and template helpers), so you might as well do it all with your web framework since having a manifest file get generated with webpack isn't enough on its own.

This is what Rails, Django, Phoenix and now Flask does (well, with Flask I wrote an [extension to do it](https://github.com/nickjj/flask-static-digest)).
